#ifndef TTY_H
#define TTY_H 1

#define FRAMEBUFFER_ADDR 0xB8000
#define FRAMEBUFFER_LENGTH 2000
#define FRAMEBUFFER_WIDTH 80
#define FRAMEBUFFER_HEIGHT 25

#define FRAMEBUFFER_SHIFT FRAMEBUFFER_WIDTH*2

#endif
